apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: navin-gateway
  namespace: navin
  labels:
    app.kubernetes.io/part-of: tdemo1
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "8090"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway
    tanzu.app.live.view.application.actuator.path: actuator
    tanzu.app.live.view.application.name: navin-gateway
spec:
  observability:
    metrics:
      prometheus:
        enabled: true
  count: 1
  host: navin.a2.fynesy.net
  api:
    serverUrl: https://navin.a2.fynesy.net
    title: Navin Demo APIs
    description: Sample basic SCG + TAP Demos
    version: 0.0.1
    groupID: navin-demo
    cors:
      allowedOrigins:
      - https://api-portal.a2.fynesy.net
      allowedMethods:
      - GET
      allowedHeaders:
      - '*'
  serviceAccount:
    name: navin-gateway-svc-acc
  extensions:
    secretsProviders:
    - name: vault-api-keys
      vault:
        roleName: api-portal-role
        path: api-portal-for-vmware-tanzu
    filters:
      apiKey:
        enabled: true
        secretsProviderName: vault-api-keys
