apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: tdemo1
    apps.tanzu.vmware.com/workload-type: web
  name: tdemo-navin
  namespace: navin
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
    - name: message
      value: | PDS supports Dentists & Team Members | Pacific Dental Services
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tfynes-pivotal/tdemo1
